// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEpo2OiDI2G08kFRVieBaGvz90RDx7RwA',
    appId: '1:416571483233:web:204c554ca5694c678d3620',
    messagingSenderId: '416571483233',
    projectId: 'attend-d8027',
    authDomain: 'attend-d8027.firebaseapp.com',
    databaseURL: 'https://attend-d8027-default-rtdb.firebaseio.com',
    storageBucket: 'attend-d8027.appspot.com',
    measurementId: 'G-ZBEVN73JTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWS096pqjQCqKt9VO6xti_W6mQgbGFNYQ',
    appId: '1:416571483233:android:9e9af379be967fb78d3620',
    messagingSenderId: '416571483233',
    projectId: 'attend-d8027',
    databaseURL: 'https://attend-d8027-default-rtdb.firebaseio.com',
    storageBucket: 'attend-d8027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-X7u50ZNI4jXsgbu0QDBsK_GyBfEHHpo',
    appId: '1:416571483233:ios:0b65ede7be0ebd768d3620',
    messagingSenderId: '416571483233',
    projectId: 'attend-d8027',
    databaseURL: 'https://attend-d8027-default-rtdb.firebaseio.com',
    storageBucket: 'attend-d8027.appspot.com',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-X7u50ZNI4jXsgbu0QDBsK_GyBfEHHpo',
    appId: '1:416571483233:ios:a09de1234b493ffe8d3620',
    messagingSenderId: '416571483233',
    projectId: 'attend-d8027',
    databaseURL: 'https://attend-d8027-default-rtdb.firebaseio.com',
    storageBucket: 'attend-d8027.appspot.com',
    iosBundleId: 'com.example.testing.RunnerTests',
  );
}
